/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HackerRoom = props => {
    const { nodes, materials } = useGLTF('/models/untitled.glb')

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled.geometry}
                material={materials.palette}
                rotation={[Math.PI / 2, 0.02, -0.1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={materials['Material.001']}
                position={[6.836, 0, -64.052]}
                scale={9.533}
            />
        </group>
    )
}

useGLTF.preload('/models/untitled.glb')

export default HackerRoom


